### PR TITLE
Revisit random-delay

### PR DESCRIPTION
**Pull request by commixon**
This is the commit message:
```
If enabled it will still delay randomly between 0-5 seconds.

However, the functionality to fine grain this is added.
Both seconds and milliseconds are supported now. Moreover,
min/max values for random delay can be condigured through
pflag params
```

First of all let me state this , I am not the most proficient Go Developer (far from it), so in case you have any objections please fire away!

Podinfo is great and I have been using it heavily. My latest use case was that I wanted to use podinfo to emulate some random delays (e.g. between 50-80 ms) to test out some fault injection cases. I thought I would add this here.

Although many more config parameters have been added, the default functionality is the same, that is if someone just enables `--random-delay true` it will ping pong between 0s-5s.

I think some validation is needed (i.e. max value should be >= min value). Also I think it makes sense to only support seconds and milliseconds, so a validation for the time unit should be in place.

I did not see a validation/sanity checking process so I would like to ask for your recommendation regarding that. Do you think it should be done in the middleware and just return an error/panic. Or a validation/sanity process for pflag arguments should be added before the actual `Server` is initiated?

### CODE REVIEW

**Comment by stefanprodan** [comment]
> I did not see a validation/sanity checking process so I would like to ask for your recommendation regarding that. Do you think it should be done in the middleware and just return an error/panic. Or a validation/sanity process for pflag arguments should be added before the actual Server is initiated?

I think the validation should be at startup and panic if the pflag validation fails.

**Comment by commixon** [comment]
Thanks @stefanprodan  I will do that later today. Other than that do you think this whole thing is valid/makes sense?

**Comment by commixon** [comment]
Added some simple validation steps.

Also I did run a `go mod tidy` (go version 1.14.4)

**Comment by stefanprodan** [comment]
@commixon this is now released as 4.0.6

**Pull request merged**
